[project]
name = "ImpactDAO"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.dao-core]
path = "contracts/dao-core.clar"
depends_on = []

[contracts.governance-token]
path = "contracts/governance-token.clar"
depends_on = []

[contracts.impact-projects]
path = "contracts/impact-projects.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
